import { readFile, access } from 'node:fs/promises';
import { resolve } from 'node:path';
const root = resolve(new URL('../', import.meta.url).pathname);
const manifest = JSON.parse(await readFile(resolve(root,'.codex-plugin/plugin.json'),'utf8'));
if (manifest.name !== 'reader-plugin' || !/^\d+\.\d+\.\d+$/.test(manifest.version)) throw new Error('Invalid plugin identity/version');
if (manifest.mcpServers !== './.mcp.json') throw new Error('Missing MCP configuration');
const mcp = JSON.parse(await readFile(resolve(root,'.mcp.json'),'utf8'));
if (mcp.mcpServers?.reader?.command !== 'node') throw new Error('Invalid local launch command');
await access(resolve(root,'dist/server/index.js')); await access(resolve(root,'dist/ui/index.html'));
const html = await readFile(resolve(root,'dist/ui/index.html'),'utf8');
if (/<script[^>]+src=|<link[^>]+rel=["']stylesheet/i.test(html)) throw new Error('MCP UI must be self-contained');
console.log('Plugin manifest, local server entry, and self-contained app resource verified. Host installation is a separate check.');
